# Generated by Django 3.2 on 2021-04-24 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_employeemodel_office'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemodel',
            name='office',
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='offices',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='first_app.officemodel'),
            preserve_default=False,
        ),
    ]
