# Generated by Django 3.2 on 2021-04-25 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('office', '0006_auto_20210425_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('offices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='office.officemodel')),
            ],
            options={
                'db_table': 'employees',
            },
        ),
    ]
