# Generated by Django 3.2 on 2021-04-24 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_employeemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='office',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='office.officemodel'),
            preserve_default=False,
        ),
    ]
