# Generated by Django 3.2 on 2021-04-25 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0005_auto_20210424_2236'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='officemodel',
            table='office',
        ),
        migrations.DeleteModel(
            name='EmployeeModel',
        ),
    ]
